name: Genesis
version: '${project.version}'
main: mintychochip.genesis.Genesis
api-version: '1.20'
commands:
  mappings:
    description: sends player mappings
  foods:
    description: sends foods
  sphere:
    description: spheres
  genesis:
    description: debug commands